name: run_tests.yml
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  Run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Run Unit Tests With unittest
        run: python -m unittest -v



