name: Run Tests
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  run_unit_tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Run Unit Tests With unittest
        run: python -m unittest -v



