name: Scheduled Build
on:
  # schedule:
  #   - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  schedule_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        run: echo "Scheduled build completed successfully!"
